insert into client (name) values ('Aphena Pharma Solutions - Tennessee, LLC');
insert into client (name) values ('NARS COSMETICS');
insert into client (name) values ('Meda Pharmaceuticals Inc.');
insert into client (name) values ('Nelco Laboratories, Inc.');
insert into client (name) values ('Proficient Rx LP');
insert into client (name) values ('OMP, INC.');
insert into client (name) values ('L. Perrigo Company');
insert into client (name) values ('Dolgencorp, LLC');
insert into client (name) values ('Par Pharmaceutical, Inc.');
insert into client (name) values ('Neutrogena Corporation');
insert into client (name) values ('Bayer HealthCare Consumer Care');
insert into client (name) values ('Roerig');
insert into client (name) values ('HyVee Inc');
insert into client (name) values ('REMEDYREPACK INC.');
insert into client (name) values ('Procter & Gamble Manufacturing Company');
insert into client (name) values ('PD-Rx Pharmaceuticals, Inc.');
insert into client (name) values ('Golden State Medical Supply, Inc.');
insert into client (name) values ('Zydus Pharmaceuticals (USA) Inc.');
insert into client (name) values ('The Mentholatum Company');
insert into client (name) values ('Rij Pharmaceutical Corporation');
insert into client (name) values ('Goodier Cosmetics LP');
insert into client (name) values ('Sandoz Inc');
insert into client (name) values ('E. FOUGERA & CO., A division of Fougera Pharmaceuticals Inc.');
insert into client (name) values ('Swiss American Products');
insert into client (name) values ('Target Corporation');
